### ISSUE TITLE
Plugin not working?

### ISSUE THREAD

**Issue by toby1kenobi** [StudioMercury/digital-publishing-tools-for-wordpress#16]
I've installed the 2.03 version, downloaded as a zip from the builds directory of this repo. This is a fresh WordPress installation, running under Apache 2.4 (PHP 5.6.5) on Windows 10 (64 bit). 

If I enter our Adobe API details under Settings/Adobe API the result is the message, "Failed. The server's response wasn't recognized." flashing up in a red bar at the top of the screen. If I check in Firefox Developer, I see a POST to /wp-admin/admin-ajax.php?action=save_settings, and the response is:

```
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>C:\Users\Toby\Documents\projects\DPS 2015\wp-test\wp-content\plugins\digital-publishing-tools-for-wordpress\classes\cms-modules\wordpress\dpsfa-cms-wordpress-ajax.php</b> on line <b>547</b><br />
{"code":300,"message":"SSL certificate problem: self signed certificate in certificate chain","options":null,"raw":null,"settings":{"company":"Sunday","key":"aaa-bbb-ccc-ddd","secret":"xxxx-xxxx-xxxx-xxxx","device_token":"GREATBIGDVEICETOKENSTRING","refresh_token":"","access_token":"","authentication_endpoint":"https:\/\/ims-na1.adobelogin.com\/","authorization_endpoint":"https:\/\/authorization.publish.adobe.io\/","ingestion_endpoint":"https:\/\/ings.publish.adobe.io\/","producer_endpoint":"https:\/\/pecs.publish.adobe.io\/","product_endpoint":"https:\/\/ps.publish.adobe.io\/","portal_url":"https:\/\/publish.adobe.com\/","request_id":"aaa-bbb-ccc-ddd-eee","tooltips":"1","auto_preview_toc":"1","preset_template":"","htmlresources":"","login":"","password":"","appMode":"app","apiVersion":"2","publications":[],"permissions":[],"devices":[],"templates":[{"name":"article.php","path":"C:\\Users\\Toby\\Documents\\projects\\DPS 2015\\wp-test\\wp-content\\plugins\\digital-publishing-tools-for-wordpress\/publish-templates\/article.php","modified":"September 29 2015 14:27:51"}],"defaultTemplate":"","defaultPublication":"","collectionDefaults":[],"importRules":[],"version":"2.0.3"}}
```

(I've obscured some of the sensitive data)

Our API details do get saved, and appear if I refresh the page, I don't think it's working though. Nothing appears under 'Authorized publications' and if I click the 'Refresh list' link an error appears in Firefox's console:

```
Error: Settings.getSettings is not a function
$scope.refresh@http://dps2015/wp-content/plugins/digital-publishing-tools-for-wordpress/app/scripts/controllers.js?ver=4.3.1:58:3
ib.prototype.functionCall/<@http://dps2015/wp-content/plugins/digital-publishing-tools-for-wordpress/app/bower_components/angular/angular.min.js?ver=4.3.1:199:301
Ec[c]</<.compile/</</f@http://dps2015/wp-content/plugins/digital-publishing-tools-for-wordpress/app/bower_components/angular/angular.min.js?ver=4.3.1:216:74
Pe/this.$get</n.prototype.$eval@http://dps2015/wp-content/plugins/digital-publishing-tools-for-wordpress/app/bower_components/angular/angular.min.js?ver=4.3.1:126:11
Pe/this.$get</n.prototype.$apply@http://dps2015/wp-content/plugins/digital-publishing-tools-for-wordpress/app/bower_components/angular/angular.min.js?ver=4.3.1:126:236
Ec[c]</<.compile/</<@http://dps2015/wp-content/plugins/digital-publishing-tools-for-wordpress/app/bower_components/angular/angular.min.js?ver=4.3.1:216:124
m.event.dispat[…]
```

Should this work ok, have I done something wrong? Let me know if I can provide any more details.

Toby

**Comment by toby1kenobi** [comment]
If it helps at all, if I connect using the PHP SDK (https://helpx.adobe.com/digital-publishing-solution/help/content-producer-service-sdk.html) using the same credentials, I can get a list of all publications to which the user associated with the API key has access, so that all seems to be ok.

**Comment by toby1kenobi** [comment]
It also seems to work ok on Ubuntu server 14.04 LTS

**Comment by StudioMercury** [comment]
@toby1kenobi the plugin uses ajax to communicate with WordPress. We've released a new version of the plugin that should help resolve some of the ajax issues with PHP warnings. You can try updating the plugin and see if this resolves you issue. I did notice you're getting an "SSL certificate problem." Ajax will not work if you have a certificate issue, so you will want to resolve that before trying it again.
